name: Title Storage

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  halo3_release:
    name: "Build Title Storage [Halo 3 Release]"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build (Halo 3 Release)
      run: ./tools/blf_cli title-storage build "./Halo 3/Release" "./title/tracked/12070" "Halo 3" 12070.08.09.05.2031.halo3_ship
    - name: Build (Halo 3 ODST)
      run: './tools/blf_cli title-storage build "./Halo 3 ODST/Release" "./title/4d530877/tracked/13895" "Halo 3: ODST" 13895.09.04.27.2201.atlas_release'
    - uses: actions/upload-artifact@v4
      with:
        name: "Title Storage"
        path: ./title

  # upload_blfs:
  #   name: "Upload BLF files"
  #   runs-on: ubuntu-latest
  #   needs: [ halo3_release]
  #   steps:
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       path: ./title
