name: Title Storage

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_title_storage:
    name: "Build Title Storage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build [Halo 3]
      run: ./tools/blf_cli title-storage build "./Halo 3/Release" "./title/tracked/12070" "Halo 3" 12070.08.09.05.2031.halo3_ship
    - name: Build [Halo 3 ODST]
      run: './tools/blf_cli title-storage build "./Halo 3 ODST/Release" "./title/4d530877/tracked/13895" "Halo 3: ODST" 13895.09.04.27.2201.atlas_release'
    - name: Build [Halo Reach]
      run: './tools/blf_cli title-storage build "./Halo Reach/Release" "./title/4d53085b/tracked/12065" "Halo: Reach" 12065.11.08.24.1738.tu1actual'
    - name: Build [Ares]
      run: './tools/blf_cli title-storage build "./Ares/Untracked" "./title/ares/untracked/username/main" "Ares" untracked'
    - uses: actions/upload-artifact@v4
      with:
        name: "Title Storage"
        path: ./title
