name: Title Storage

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_title_storage:
    name: "Build Title Storage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build [Halo 3]
      run: |
        ./tools/blf_cli title-storage build "./Halo 3/Release" "./title/tracked/12070" "Halo 3" 12070.08.09.05.2031.halo3_ship
        ./tools/blf_cli title-storage build "./Halo 3/Epsilon" "./title/tracked/11856" "Halo 3" 11856.07.08.20.2332.release
        ./tools/blf_cli title-storage build "./Halo 3/Release" "./title/tracked/11855" "Halo 3" 11856.07.08.20.2332.release
        ./tools/blf_cli title-storage build "./Halo 3/11729.07.08.10.0021.main" "./title/tracked/11729" "Halo 3" 11729.07.08.10.0021.main
        ./tools/blf_cli title-storage build "./Halo 3/Epsilon" "./title/tracked/11637" "Halo 3" 11637.07.08.02.2348.release
        ./tools/blf_cli title-storage build "./Halo 3/Delta" "./title/tracked/10015" "Halo 3" 10015.07.05.14.2217.delta
        ./tools/blf_cli title-storage build "./Halo 3/Delta" "./title/tracked/09699" "Halo 3" 10015.07.05.14.2217.delta
        ./tools/blf_cli title-storage build "./Halo 3/08172.07.03.08.2240.delta" "./title/tracked/08172" "Halo 3" 08172.07.03.08.2240.delta
        ./tools/blf_cli title-storage build "./Halo 3/08117.07.03.07.1702.delta" "./title/tracked/08117" "Halo 3" 08117.07.03.07.1702.delta
        ./tools/blf_cli title-storage build "./Halo 3/06481.06.11.17.1330.alpha_release" "./title/tracked/06481" "Halo 3" 06481.06.11.17.1330.alpha_release     
    - name: Build [Halo 3 ODST]
      run: './tools/blf_cli title-storage build "./Halo 3 ODST/Release" "./title/4d530877/tracked/13895" "Halo 3: ODST" 13895.09.04.27.2201.atlas_release'
    - name: Build [Halo Reach]
      run: |
        ./tools/blf_cli title-storage build "./Halo Reach/Release" "./title/4d53085b/tracked/12065" "Halo: Reach" 12065.11.08.24.1738.tu1actual
        ./tools/blf_cli title-storage build "./Halo Reach/Delta" "./title/4d53885c/tracked/09730" "Halo: Reach" 09730.10.04.09.1309.omaha_delta
        ./tools/blf_cli title-storage build "./Halo Reach/Beta" "./title/4d53885c/tracked/09664" "Halo: Reach" 09730.10.04.09.1309.omaha_delta
        ./tools/blf_cli title-storage build "./Halo Reach/Beta" "./title/4d53885c/tracked/09449" "Halo: Reach" 09449.10.03.25.1545.omaha_beta
        ./tools/blf_cli title-storage build "./Halo Reach/Alpha" "./title/4d53885c/tracked/08516" "Halo: Reach" 08516.10.02.19.1607.omaha_alpha
    - name: Build [Ares]
      run: './tools/blf_cli title-storage build "./Ares/Untracked" "./title/ares/untracked/username/main" "Ares" untracked'
    - name: Build [Halo Online]
      run: './tools/blf_cli title-storage build "./Halo Online" "./title/4d530877/donkey/tracked/106708" "Halo: Online" 1.106708_cert_ms23___release'
    - uses: actions/upload-artifact@v4
      with:
        name: "Title Storage"
        path: ./title