name: Title Storage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  halo3_release:
    name: "Build Title Storage [Halo 3 Release]"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./tools/blf_cli build-title-storage "./Halo 3//Release" "title/tracked/12070" "Halo 3" 12070.08.09.05.2031.halo3_ship
  
  upload_blfs:
    name: "Upload BLF files"
    runs-on: ubuntu-latest
    needs: [ haloe_release]
    - uses: actions/upload-artifact@v4
      with:
        path: title/*
